name: SynapseInjector Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build the application
      # FIX: Added the subfolder path to the vcxproj file
      run: msbuild SynapseInjector/SynapseInjector.vcxproj /p:Configuration=Release /p:Platform=x64

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Injector-Executable
        # FIX: Added the subfolder path to the output directory
        path: SynapseInjector/x64/Release/*.exe
